main: com.windstudio.discordwl.Main
name: DiscordWhitelist
description: Modern server security automation
author: "WIND STUDIO"
version: ${project.version}
api-version: 1.14
folia-supported: false
softdepend: [SuperVanish, PremiumVanish, Essentials, CMI, AdvancedVanish, SayanVanish]
commands:
  link:
    usage: /<command>
    description: Command to link your account
  account:
    usage: /<command>
    description: Command to get information about your linked account
  ewhitelist:
    aliases: [ ewl ]
    permission: [ dswl.admin ]
    description: Whitelist management command
permissions:
  dswl.admin:
    description: Allows to use all commands
    default: op